### ISSUE TITLE
Error when running `run_co3d_sp` script

### ISSUE THREAD

**Issue by greeneggsandyaml** [leonidk/fmb-plus#1]
Hello, thanks for your work. 

I'm getting the following error when running `run_co3d_sp`. I have not modified anything. 

```
Traceback (most recent call last):
  File "/fsx-repligen/lukemelas/dev/tmp/fmb-plus/run_co3d_sp.py", line 362, in <module>
    mask = (all_sils !=0 ) & (~np.isnan(d1f)) & (~np.isnan(d2f)) & (d1f !=0)
  File "/data/home/lukemelas/mambaforge/envs/fmb/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 251, in deferring_binary_op
    return binary_op(*args)
  File "/data/home/lukemelas/mambaforge/envs/fmb/lib/python3.10/site-packages/jax/_src/numpy/ufuncs.py", line 81, in <lambda>
    fn = lambda x1, x2, /: lax_fn(*promote_args(numpy_fn.__name__, x1, x2))
TypeError: and got incompatible shapes for broadcasting: (25468968,), (50937936,).
```

The full output of the script before the error is as follows:
```
❯ python run_co3d_sp.py
 epoch:   0%|          | 0/10 [00:00<?, ?it/s]
 iteration:   0%|          | 0/509 [00:00<?, ?it/s]
 iteration:   0%|          | 0/509 [00:00<?, ?it/s]
dropping LR to 8.00e-03 after 643 steps
dropping LR to 8.00e-04 after 821 steps
dropping LR to 8.00e-05 after 999 steps
early exit due to no progress
(47, 3)
Traceback (most recent call last):
...
```
then the traceback above. 

I also get the same error with the `zpfm` version.

Have you gotten this before / do you know what might be going wrong?

Thanks for your help!

**Comment by greeneggsandyaml** [comment]
Update: I commented out the line with the issue and everything works fine afterwards.
